library(tidyverse)
library(plyr)
dry <- read.csv("Dry_Weight/combined_dry.csv", header=T, stringsAsFactors=F)
str(dry)
wet <- read.csv("Wet_Weight/combined_wet.csv", header=T, stringsAsFactors=F)
str(wet)
wet.dry <-join(wet, dry, by="FruitID") 
wet.dry <- wet.dry %>% mutate(DM = (Dry/Wet)*100)
final <- data.frame(FruitID=wet.dry$FruitID, DM= wet.dry$DM, stringsAsFactors=F)
str(final)
write.csv(final, "DM.csv", quote=F, row.names=F)
